{{- $appProxyContext := deepCopy . }}
{{- $_ := set $appProxyContext "Values" (deepCopy (get .Values "app-proxy")) }}
{{- $_ := set $appProxyContext.Values "global" (deepCopy (get .Values "global")) }}
{{- if (index  (get $appProxyContext "Values") "image-enrichment" "enabled") }}
{{- include "cap-app-proxy.image-enrichment.resources.sa" $appProxyContext }}
{{- end }}
