
{{- if index (get .Values "argo-workflows") "enabled" }}
  {{- $eventReporterContext := deepCopy . }}
  {{- $_ := set $eventReporterContext "Values" (deepCopy (get .Values "event-reporters")) }}
  {{- $_ := set $eventReporterContext.Values "global" (deepCopy (get .Values "global")) }}
  {{- include "event-reporters.workflow-reporter.sa" $eventReporterContext }}
{{- end }}
