{{- define "argo-cd.namespaced-rbac.secret" }}
apiVersion: v1
kind: Secret
metadata:
  name: argocd-manager-long-lived-token
  annotations:
    kubernetes.io/service-account.name: argocd-manager
type: kubernetes.io/service-account-token
{{- end }}
