{{- define "runtime-reporter.resources.configmap.defaults"}}
argocd.server: {{ include "codefresh-gitops-runtime.argocd.server.no-protocol-url" . }}
redis.server: {{ include "codefresh-gitops-runtime.argocd.redis.url" . }}
repo.server: {{ include "codefresh-gitops-runtime.argocd.reposerver.url" . }}
sources.server: http://argo-api-gateway
app.queue.size: '1000'
max.app.retries: '5'
threadiness: '100'
{{- end }}

{{- $defaultConfig := (include "runtime-reporter.resources.configmap.defaults" . | fromYaml ) }}
{{- $overrides := index .Values "event-reporters" "runtime-reporter" "config" | default dict }}
{{- $mergedConfig := mergeOverwrite $defaultConfig $overrides }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: runtime-reporter-cmd-params-cm
  labels:
    {{- include "runtime-reporter.labels" . | nindent 4 }}
data:
  {{- $mergedConfig | toYaml | nindent 2 }}
