{{- if or (index (get .Values "argo-rollouts") "enabled") (index .Values "event-reporters" "rollout" "external-argo-rollouts" "enabled") }}
  {{- $eventReporterContext := deepCopy . }}
  {{- $_ := set $eventReporterContext "Values" (deepCopy (get .Values "event-reporters")) }}
  {{- $_ := set $eventReporterContext.Values "global" (deepCopy (get .Values "global")) }}
  {{- include "event-reporters.rollout-reporter.eventsource" $eventReporterContext }}
{{- end }}
