{{- if or (index (get .Values "argo-rollouts") "enabled") (and (not (index (get .Values "argo-rollouts") "enabled")) (index .Values.global "external-argo-rollouts" "rollout-reporter" "enabled" )) }}
  {{- $eventReporterContext := deepCopy . }}
  {{- $_ := set $eventReporterContext "Values" (deepCopy (get .Values "event-reporters")) }}
  {{- $_ := set $eventReporterContext.Values "global" (deepCopy (get .Values "global")) }}
  {{- include "event-reporters.rollout-reporter.sensor" $eventReporterContext }}
{{- end }}
