{{- if or (index (get .Values "argo-rollouts") "enabled") (and (not (index (get .Values "argo-rollouts") "enabled")) (index .Values.global "external-argo-rollouts" "rollout-reporter" "enabled" )) }}
  {{- $eventReporterContext := deepCopy . }}
  {{- $_ := set $eventReporterContext "Values" (deepCopy (get .Values "event-reporters")) }}
  {{- $_ := set $eventReporterContext.Values "global" (deepCopy (get .Values "global")) }}

  {{/* Proxy environment variables */}}
  {{- if .Values.global.httpProxy }}
    {{- $_ := set $eventReporterContext.Values.rollout.sensor.env "HTTP_PROXY" .Values.global.httpProxy }}
  {{- end }}
  {{- if .Values.global.httpsProxy }}
    {{- $_ := set $eventReporterContext.Values.rollout.sensor.env "HTTPS_PROXY" .Values.global.httpsProxy }}
  {{- end }}
  {{- if .Values.global.noProxy }}
    {{- $_ := set $eventReporterContext.Values.rollout.sensor.env "NO_PROXY" .Values.global.noProxy }}
  {{- end }}

  {{- include "event-reporters.rollout-reporter.sensor" $eventReporterContext }}
{{- end }}
