global:
  runtime:
    isConfigurationRuntime: false

sealed-secrets:
  enabled: false

argo-cd:
  createClusterRoles: false
  crds:
    install: false

  configs:
    params:
      application.namespaces: ""

argo-events:
  controller:
    rbac:
      namespaced: true

argo-workflows:
  crds:
    install: false

  singleNamespace: true
  createAggregateRoles: false
  controller:
    clusterWorkflowTemplates:
      enabled: false

  server:
    clusterWorkflowTemplates:
      enabled: false

argo-rollouts:
  installCRDs: false
  clusterInstall: false

tunnel-client:
  enabled: false

app-proxy:
  singleNamespace: true

gitops-operator:
  enabled: false
  # crds:
  #   install: false

  # singleNamespace: true
  # image:
  #   tag: feat-cr-24670-namespaced-install-521a5ee
