{{- $eventBusName := (include "codefresh-gitops-runtime.eventbus.name" .Values.global.runtime.eventBus) }}
{{- $eventBusSpec := .Values.global.runtime.eventBus }}
{{- $eventBusType := .Values.global.runtime.eventBus.type }}
{{/* Remove name from eventbus spec */}}
{{- if hasKey $eventBusSpec "name" }}
{{- $eventBusSpec = unset $eventBusSpec "name" }}
{{- end }}
{{/* Remove pdb from eventbus spec */}}
{{- if hasKey $eventBusSpec "pdb" }}
{{- $eventBusSpec = unset $eventBusSpec "pdb" }}
{{- end }}
{{/* Remove annotations from eventbus spec */}}
{{- if hasKey $eventBusSpec "annotations" }}
{{- $eventBusSpec = unset $eventBusSpec "annotations" }}
{{- end }}

{{- if eq $eventBusType "nats" }}
  {{- $eventBusSpec = unset $eventBusSpec "jetstream" }}
  {{- $_ := set $eventBusSpec.nats.native "nodeSelector" ($eventBusSpec.nats.native.nodeSelector | default .Values.global.nodeSelector) }}
  {{- $_ := set $eventBusSpec.nats.native "tolerations" ($eventBusSpec.nats.native.tolerations | default .Values.global.tolerations) }}
{{- end }}

{{- if eq $eventBusType "jetstream" }}
  {{- $eventBusSpec = unset $eventBusSpec "nats" }}
  {{- $_ := set $eventBusSpec.jetstream "nodeSelector" ($eventBusSpec.jetstream.nodeSelector | default .Values.global.nodeSelector) }}
  {{- $_ := set $eventBusSpec.jetstream "tolerations" ($eventBusSpec.jetstream.tolerations | default .Values.global.tolerations) }}
{{- end }}

apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: {{ $eventBusName }}
  annotations:
    {{- .Values.global.runtime.eventBus.annotations | toYaml | nindent 4}}
  labels:
    app.kubernetes.io/part-of: codefresh-eventbus
    codefresh.io/internal: "true"
spec:
  {{- $eventBusSpec | toYaml | nindent 2}}
