{{- $eventBusName := default "codefresh-eventbus" .Values.global.runtime.eventBus.name }}
{{- $eventBusSpec := .Values.global.runtime.eventBus }}
{{/* Remove name from eventbus spec */}}
{{- if hasKey $eventBusSpec "name" }}
{{- $eventBusSpec = unset $eventBusSpec "name" }}
{{- end }}
{{/* Remove pdb from eventbus spec */}}
{{- if hasKey $eventBusSpec "pdb" }}
{{- $eventBusSpec = unset $eventBusSpec "pdb" }}
{{- end }}
{{- if hasKey $eventBusSpec "annotations" }}
{{- $eventBusSpec = unset $eventBusSpec "annotations" }}
{{- end }}

{{- $_ := set $eventBusSpec.nats.native "nodeSelector" ($eventBusSpec.nats.native.nodeSelector | default .Values.global.nodeSelector) }}
{{- $_ := set $eventBusSpec.nats.native "tolerations" ($eventBusSpec.nats.native.tolerations | default .Values.global.tolerations) }}

apiVersion: argoproj.io/v1alpha1
kind: EventBus
metadata:
  name: {{ $eventBusName }}
  annotations:
    {{- .Values.global.runtime.eventBus.annotations | toYaml | nindent 4}}
  labels:
    app.kubernetes.io/part-of: argo-events
    codefresh.io/internal: "true"
spec:
  {{- $eventBusSpec | toYaml | nindent 2}}
