{{- $eventBusName := (include "codefresh-gitops-runtime.eventbus.name" .Values.global.runtime.eventBus) }}
{{- if .Values.global.runtime.eventBus.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $eventBusName }}
spec:
  minAvailable: 2
  selector:
    matchLabels:
      eventbus-name: {{ $eventBusName }}
{{- end }}