{{- $internalRouterContext := deepCopy . }}
{{- $_ := set $internalRouterContext "Values" (deepCopy (get .Values "internal-router")) }}
{{- $_ := set $internalRouterContext.Values "global" (deepCopy (get .Values "global")) }}

{{- if $internalRouterContext.Values.pdb.enabled }}
{{- include "internal-router.resources.pdb" $internalRouterContext }}
{{- end }}
