{{- $internalRouterContext := deepCopy . }}
{{- $_ := set $internalRouterContext "Values" (get .Values "internal-router") }}
{{- $_ := set $internalRouterContext.Values "global" (get .Values "global") }}

{{- if $internalRouterContext.Values.pdb.enabled }}
{{- include "internal-router.resources.pdb" $internalRouterContext }}
{{- end }}
