{{- $internalRouterContext := deepCopy . }}
{{- $_ := set $internalRouterContext "Values" (deepCopy (get .Values "internal-router")) }}
{{- $_ := set $internalRouterContext.Values "global" (deepCopy (get .Values "global")) }}
{{- include "internal-router.resources.service" $internalRouterContext }}
