{{- if index .Values "argo-cd" "acrController" "enabled" }}
{{- $config := index .Values "argo-cd" "acrController" "clusterAdminAccess" | default dict -}}
{{- if hasKey $config "enabled" | ternary $config.enabled .Values.createClusterRoles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "argo-cd.acr-controller.fullname" . }}
  labels:
    {{- include "argo-cd.labels" (dict "context" . "component" index .Values "argo-cd" "acrController" "name" "name" index .Values "argo-cd" "acrController" "name") | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "argo-cd.acr-controller.fullname" . }}
subjects: 
- kind: ServiceAccount
  name: {{ include "argo-cd.acrControllerServiceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
