{{- if index .Values "argo-cd" "acrController" "enabled" }}
{{- $config := index .Values "argo-cd" "acrController" "clusterAdminAccess" | default dict -}}
{{- if hasKey $config "enabled" | ternary $config.enabled .Values.createClusterRoles }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "argo-cd.acr-controller.fullname" . }}
  labels:
    {{- include "argo-cd.labels" (dict "context" . "component" index .Values "argo-cd" "acrController" "name" "name" index .Values "argo-cd" "acrController" "name") | nindent 4 }}
rules:
  {{- if index .Values "argo-cd" "acrController" "clusterRoleRules.enabled" }}
    {{- toYaml index .Values "argo-cd" "acrController" "clusterRoleRules" "rules" | nindent 2 }}
  {{- else }}
  - apiGroups:
      - argoproj.io
    resources:
      - applications
    verbs:
      - get
      - list
      - watch
      - patch
      - update
{{- end }}
{{- end }}
{{- end }}
