{{- if and index .Values "argo-cd" "acrController" "enabled" index .Values "argo-cd" "acrController" "serviceAccount" "create" }}
apiVersion: v1
kind: ServiceAccount
automountServiceAccountToken: {{ index .Values "argo-cd" "acrController" "serviceAccount" "automountServiceAccountToken" }}
metadata:
  name: {{ template "argo-cd.acrController.serviceAccountName" . }}
  namespace: {{ .Release.Namespace | quote }}
{{- if index .Values "argo-cd" "acrController" "serviceAccount" "annotations"}}
  annotations:
  {{- range $key, $value := index .Values "argo-cd" "acrController" "serviceAccount" "annotations" }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
  labels:
    {{- include "argo-cd.labels" (dict "context" . "component" index .Values "argo-cd" "acrController" "name" "name" index .Values "argo-cd" "acrController" "name") | nindent 4 }}
  {{- range $key, $value := index .Values "argo-cd" "acrController" "serviceAccount" "labels" }}
    {{ $key }}: {{ $value | quote }}
  {{- end }}
{{- end }}
