{{- $context := deepCopy . }}
{{- $_ := set $context "Values" (deepCopy (get .Values "argo-gateway")) }}
{{- $_ := set $context.Values "global" (deepCopy (get .Values "global")) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "argo-gateway.fullname" . }}
  labels:
    {{- include "argo-gateway.labels" . | nindent 4 }}
spec:
  type: {{ $context.Values.service.type | default "ClusterIP" }}
  ports:
    - port: {{ $context.Values.service.port | default 80 }}
      targetPort: {{ $context.Values.service.targetPort | default "http" }}
      protocol: TCP
      name: http
  selector:
    {{- include "argo-gateway.selectorLabels" . | nindent 4 }}
