{{- define "gitops-operator.resources" }}
---
  {{ include "gitops-operator.resources.deployment" . }}
---
  {{ include "gitops-operator.resources.rbac" . }}
---
  {{ include "gitops-operator.resources.auth_proxy_rbac" . }}
---
  {{ include "gitops-operator.resources.leader_election_rbac" . }}
---
  {{ include "gitops-operator.resources.restricted_git_source_rbac" . }}
---
  {{ include "gitops-operator.resources.sa" .}}
---
  {{- include "gitops-operator.crds.restricted-gitsource" . }}
{{- end }}