{{- define "gitops-operator.resources.promotion-template" }}

{{- $context := deepCopy . }}

{{- $defaultVals := include "gitops-operator.default-values" . | fromYaml }}
{{- $vals := mergeOverwrite $defaultVals (get .Values "gitops-operator") }}

{{- $_ := set $context "Values" $vals }}
{{- $_ := set $context.Values "global" (deepCopy (get .Values "global")) }}

  {{- include "gitops-operator.resources.promotion-template-sa" $context }}
---
  {{- include "gitops-operator.resources.promotion-template-rbac" $context }}
{{- end }}
