
{{- define "gitops-operator.resources.promotion-template-rbac" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.singleNamespace | ternary "Role" "ClusterRole" }}
metadata:
  labels:
    {{- include "gitops-operator.selectorLabels" . | nindent 4 }}
  name: promotion-template
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - patch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
- apiGroups:
  - argoproj.io
  resources:
  - workflows
  verbs:
  - create
  - get
  - list
  - patch
  - watch
- apiGroups:
  - argoproj.io
  resources:
  - workflowtemplates
  verbs:
  - get
- apiGroups:
  - argoproj.io
  resources:
  - workflowtaskresults
  verbs:
  - create
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.singleNamespace | ternary "RoleBinding" "ClusterRoleBinding" }}
metadata:
  labels:
    {{- include "gitops-operator.selectorLabels" . | nindent 4 }}
  name: promotion-template
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ .Values.singleNamespace | ternary "Role" "ClusterRole" }}
  name: promotion-template
subjects:
- kind: ServiceAccount
  name: {{ include "gitops-operator.promotionTemplate.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
