{{- define "gitops-operator.resources.promotion-template-sa" }}
  {{- if .Values.promotionTemplate.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gitops-operator.promotionTemplate.serviceAccountName" . }}
  labels:
    {{- include "gitops-operator.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
