{{- define "cap-app-proxy.resources.configmap" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cap-app-proxy-cm
  labels:
    {{- include "cap-app-proxy.labels" . | nindent 4 }}
data:
  argoCdUrl: {{ .Values.config.argoCdUrl }}
  argoCdUsername: {{ .Values.config.argoCdUsername }}
  argoWorkflowsInsecure: {{ .Values.config.argoWorkflowsInsecure | quote }}
  env: {{ .Values.config.env }}
  argoWorkflowsUrl: {{ default "" .Values.config.argoWorkflowsUrl }}
  runtimeName: {{ .Values.global.runtime.name }}
  {{- $enrichmentValues := get .Values "image-enrichment" }}
  {{- if $enrichmentValues.enabled }}
  enrichmentConcurrencyCmName: {{ $enrichmentValues.config.concurrencyCmName }}
  enrichmentConcurrencyCmKey: {{ $enrichmentValues.config.concurrencyCmKey }}
  enrichmentServiceAccountName: {{ $enrichmentValues.serviceAccount.name }}
  enrichmentPodGcStrategy: {{ $enrichmentValues.config.podGcStrategy }}
  enrichmentTtlAfterCompletionInSeconds: {{ $enrichmentValues.config.ttlAfterCompletionInSeconds | quote }}
  enrichmentTtlActiveInSeconds: {{ $enrichmentValues.config.ttlActiveInSeconds | quote }}
  enrichmentClientHeartbeatIntervalInSeconds: {{ $enrichmentValues.config.clientHeartbeatIntervalInSeconds | quote }}
  {{- end }}
{{- end }}
