{{- define "cap-app-proxy.resources.configmap-documented-configs"}}
argoCdUrl: {{ .Values.argoCdCredentials.url }}
argoCdUsername: {{ .Values.argoCdCredentials.username }}
argoWorkflowsUrl: {{ default "" .Values.config.argoWorkflowsUrl }}
argoWorkflowsInsecure: {{ .Values.config.argoWorkflowsInsecure | quote }}
skipGitPermissionValidation: {{ .Values.config.skipGitPermissionValidation | quote }}
logLevel: {{ .Values.config.logLevel | quote }}
cors: {{ .Values.global.codefresh.url }}
env: {{ .Values.config.env | quote}}
isConfigurationRuntime: {{ .Values.global.runtime.isConfigurationRuntime | quote }} 
runtimeName: {{ required "global.runtime.name is required" .Values.global.runtime.name | quote}}
  {{- $enrichmentValues := get .Values "image-enrichment" }}
  {{- if $enrichmentValues.enabled }}
enrichmentConcurrencyCmName: {{ $enrichmentValues.config.concurrencyCmName | quote}}
enrichmentConcurrencyCmKey: {{ $enrichmentValues.config.concurrencyCmKey | quote}}
enrichmentServiceAccountName: {{ $enrichmentValues.serviceAccount.name | quote}}
enrichmentPodGcStrategy: {{ $enrichmentValues.config.podGcStrategy | quote}}
enrichmentTtlAfterCompletionInSeconds: {{ $enrichmentValues.config.ttlAfterCompletionInSeconds | quote }}
enrichmentTtlActiveInSeconds: {{ $enrichmentValues.config.ttlActiveInSeconds | quote }}
enrichmentClientHeartbeatIntervalInSeconds: {{ $enrichmentValues.config.clientHeartbeatIntervalInSeconds | quote }}
enrichmentImageReportingImage: {{ printf "%s/%s:%s" $enrichmentValues.config.images.reportImage.registry $enrichmentValues.config.images.reportImage.repository $enrichmentValues.config.images.reportImage.tag | quote }}
enrichmentGitEnrichmentImage: {{ printf "%s/%s:%s" $enrichmentValues.config.images.gitEnrichment.registry $enrichmentValues.config.images.gitEnrichment.repository $enrichmentValues.config.images.gitEnrichment.tag | quote }}
enrichmentJiraEnrichmentImage: {{ printf "%s/%s:%s" $enrichmentValues.config.images.jiraEnrichment.registry $enrichmentValues.config.images.jiraEnrichment.repository $enrichmentValues.config.images.jiraEnrichment.tag | quote }}
  {{- end }}
{{- end }}

{{- define "cap-app-proxy.resources.configmap" }}
{{- $documentedConfigs := (include "cap-app-proxy.resources.configmap-documented-configs" . | fromYaml ) }}
{{- $overrides := .Values.config }}
{{- $mergedConfig := mergeOverwrite $documentedConfigs $overrides }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: cap-app-proxy-cm
  labels:
    {{- include "cap-app-proxy.labels" . | nindent 4 }}
data:
  {{- $mergedConfig | toYaml | nindent 2}}
{{- end }}
