
{{- define "cap-app-proxy.resources.rbac" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    app: cap-app-proxy
  name: cap-app-proxy
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - configmaps
  - pods
  verbs:
  - get
  - create
  - delete
  - deletecollection
  - update
  - patch
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - services
  verbs:
  - get
  - list
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - get
  - list
  - patch
- apiGroups:
  - argoproj.io
  resources:
  - applications
  - applicationsets
  - appprojects
  verbs:
  - create
  - get
  - list
  - watch
  - update
  - delete
  - patch
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app: cap-app-proxy
  name: cap-app-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cap-app-proxy
subjects:
- kind: ServiceAccount
  name: {{ include "cap-app-proxy.serviceAccountName" . }}
{{- end }}
