{{- define "cap-app-proxy.resources.sa" }}
  {{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "cap-app-proxy.serviceAccountName" . }}
  labels:
    {{- include "cap-app-proxy.labels" . | nindent 4 }}
    {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}