{{- define "cap-app-proxy.resources.service" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cap-app-proxy.fullname" . }}
  labels:
    {{- include "cap-app-proxy.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cap-app-proxy.selectorLabels" . | nindent 4 }}
{{- end }}