{{- $gitopsOperatorContext := deepCopy . }}
{{- $_ := set $gitopsOperatorContext "Values" (get .Values "gitops-operator") }}
{{- $_ := set $gitopsOperatorContext.Values "global" (get .Values "global") }}

{{ include "gitops-operator.resources.sa" $gitopsOperatorContext }}