global:
  imagePullSecrets:
    - name: dockerhub-creds
  codefresh:
    accountId: 63dbba4928d5fd1ef065b781 # `gitops-helm-test` Codefresh account (see "gitops-runtime-helm CI" note in 1Password)
    userToken:
      token: "dummy" # set in `gitops-runtime-helm/ci` pipeline (see "gitops-runtime-helm CI" note in 1Password)

  runtime:
    name: "dummy" # set in `gitops-runtime-helm/ci` pipeline

    ingress:
      enabled: true
      className: haproxy-ingress
      hosts:
        - "runtime.example.com" # set in `gitops-runtime-helm/ci` pipeline

    repoCredentialsTemplate:
      url: 'https://github.com'
      username: 'username'
      password: 'dummy'

internal-router:
  imagePullSecrets:
    - name: dockerhub-creds
