global:
  codefresh:
    accountId: 63dbba4928d5fd1ef065b781 # Codefresh Account id for ilia-codefresh for now, needs to be some test account
    userToken:
      secretKeyRef:
        name: mysecret
        key: myvalue
        optional: true

  runtime:
    name: default
    cluster: test-cluster

    ingress:
      className: "nginx"
      hosts:
      - runtime.codefresh.local

    repoCredentialsTemplate:
      url: 'https://github.com'
      username: 'username'
      password: 'dummy'
