global:
  codefresh:
    accountId: 63dbba4928d5fd1ef065b781 # `gitops-helm-test` Codefresh account
    userToken:
      token: "" # set in `gitops-runtime-helm/ci` pipeline

  runtime:
    name: "" # set in `gitops-runtime-helm/ci` pipeline

    ingress:
      enabled: true
      className: haproxy-ingress
      hosts: [] # set in `gitops-runtime-helm/ci` pipeline

    repoCredentialsTemplate:
      url: 'https://github.com'
      username: 'username'
      password: 'dummy'
