global:
  codefresh:
    accountId: 63dbba4928d5fd1ef065b781 # `gitops-helm-test` Codefresh account
    userToken:
      token: "dummy" # set in `gitops-runtime-helm/ci` pipeline

  runtime:
    name: "dummy" # set in `gitops-runtime-helm/ci` pipeline

    ingress:
      enabled: true
      className: haproxy-ingress
      hosts:
        - "runtime.example.com" # set in `gitops-runtime-helm/ci` pipeline

    repoCredentialsTemplate:
      url: 'https://github.com'
      username: 'username'
      password: 'dummy'

argo-cd:
  enabled: false

garage-workflows-artifact-storage:
  enabled: true
