{{- $redisHa := index .Values "redis-ha" }}
{{- if and .Values.redis.enabled .Values.redis.serviceAccount.create (not $redisHa.enabled) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "redis.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.redis.serviceAccount.annotations }}
  annotations:
    {{- range $key, $value := . }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
  {{- end }}
  labels:
    {{- include "redis.labels" . | nindent 4 }}
{{- end }}
