{{- define "cf-argocd-extras.event-reporter.configmap" }}

{{- $context := deepCopy . }}

{{- $defaultVals := include "cf-argocd-extras.default-values" . | fromYaml }}
{{- $vals := mergeOverwrite $defaultVals (get .Values "cf-argocd-extras") }}

{{- $_ := set $context "Values" $vals.eventReporter }}
{{- $_ := set $context.Values "global" (deepCopy (get .Values "global")) }}

{{- $_ := set (index $context.Values.configMaps "cmd-params-cm" "data") "argocd.server" (include "codefresh-gitops-runtime.argocd.server.no-protocol-url" . ) }}
{{- $_ := set (index $context.Values.configMaps "cmd-params-cm" "data") "redis.server" (include "codefresh-gitops-runtime.argocd.redis.url" . ) }}
{{- $_ := set (index $context.Values.configMaps "cmd-params-cm" "data") "repo.server" (include "codefresh-gitops-runtime.argocd.reposerver.url" . ) }}

{{/* Workaround to NOT change label selectors from previous runtime release when event-reporter was part of cf-argocd-extras Subchart */}}
{{- $_ := set $context.Values "nameOverride" "cf-argocd-extras" }}

{{- $templateName := printf "cf-common-%s.configmaps" (index .Subcharts "cf-common").Chart.Version }}
{{- include $templateName $context }}

{{- end }}
