{{- $appProxyContext := deepCopy . }}
{{- $_ := set $appProxyContext "Values" (deepCopy (get .Values "app-proxy")) }}
{{- $_ := set $appProxyContext.Values "global" (deepCopy (get .Values "global")) }}
{{- $_ := set $appProxyContext.Values "argo-cd" (get .Values "argo-cd") }}

{{/* Merge environment variables with the ones in _app-proxy-env.yaml */}}
{{- $mainContainerMergedValues := mergeOverwrite $appProxyContext.Values.env (include "codefresh-gitops-runtime.app-proxy.calculated-env-vars" . | fromYaml) }}
{{- $_ := set $appProxyContext.Values "env" $mainContainerMergedValues }}

{{/* Add extra volumes (used for cutom tls) */}}
{{- $calculatedVolumes := include "codefresh-gitops-runtime.app-proxy.extra-volumes" . | fromYaml }}
{{- if $calculatedVolumes.extraVolumes }}
  {{- $additionalVolumes := concat (get $calculatedVolumes "extraVolumes") $appProxyContext.Values.extraVolumes }}
  {{- $_ := set $appProxyContext.Values "extraVolumes" $additionalVolumes }}
{{- end }}

{{- $initContainerCalculatedVolumeMounts := include "codefresh-gitops-runtime.app-proxy.init.extra-volume-mounts" . | fromYaml }}
{{- if $initContainerCalculatedVolumeMounts.extraVolumeMounts }}
  {{- $initContainerExtraVolumeMounts := concat (get $initContainerCalculatedVolumeMounts "extraVolumeMounts") $appProxyContext.Values.extraVolumeMounts }}
  {{- $_ := set $appProxyContext.Values.initContainer "extraVolumeMounts" $initContainerExtraVolumeMounts }}
{{- end }}

{{- $nodeSelector := $appProxyContext.Values.nodeSelector | default dict }}
{{- $globalNodeSelector := .Values.global.nodeSelector | default dict }}
{{- $allNodeSelector := mergeOverwrite $globalNodeSelector $nodeSelector }}
{{- $_ := set $appProxyContext.Values "nodeSelector" $allNodeSelector }}

{{- $tolerations := $appProxyContext.Values.tolerations | default list }}
{{- $globalTolerations := .Values.global.tolerations | default list }}
{{- $allToleration := concat $globalTolerations $tolerations }}
{{- $_ := set $appProxyContext.Values "tolerations" $allToleration }}

{{- $affinity := $appProxyContext.Values.affinity | default dict }}
{{- $globalAffinity := .Values.global.affinity | default dict }}
{{- $allAffinity := mergeOverwrite $globalAffinity $affinity }}
{{- $_ := set $appProxyContext.Values "affinity" $allAffinity }}

{{- include "cap-app-proxy.resources.deployment" $appProxyContext }}
