{{- $externalArgoCDValues := (index .Values "global" "external-argo-cd" "auth") }}
{{- if $externalArgoCDValues.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gitops-runtime-argo-cd-password
  labels:
    {{- include "codefresh-gitops-runtime.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ $externalArgoCDValues.password }}
{{- end }}

{{- if $externalArgoCDValues.token }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gitops-runtime-argo-cd-token
  labels:
    {{- include "codefresh-gitops-runtime.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ $externalArgoCDValues.token }}
{{- end }}
