{{- $argoCdAuth := (index .Values "global" "integrations" "argo-cd" "server" "auth") }}
{{- if $argoCdAuth.password }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gitops-runtime-argo-cd-password
  labels:
    {{- include "codefresh-gitops-runtime.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ $argoCdAuth.password }}
{{- end }}

{{- if $argoCdAuth.token }}
---
apiVersion: v1
kind: Secret
metadata:
  name: gitops-runtime-argo-cd-token
  labels:
    {{- include "codefresh-gitops-runtime.labels" . | nindent 4 }}
type: Opaque
stringData:
  token: {{ $argoCdAuth.token }}
{{- end }}
