{{- $appProxyContext := deepCopy . }}
{{- $_ := set $appProxyContext "Values" (deepCopy (get .Values "app-proxy")) }}
{{- $_ := set $appProxyContext.Values "global" (deepCopy (get .Values "global")) }}

{{- if $appProxyContext.Values.pdb.enabled }}
{{- include "cap-app-proxy.resources.pdb" $appProxyContext }}
{{- end }}
