{{/* Check if installation token is string or secretKeyRef and add the value with currect structure to app-proxy values */}}
{{ $appProxyContext := deepCopy . }}
{{ $_ := set $appProxyContext "Values" (get .Values "app-proxy") }}
{{ $_ := set $appProxyContext.Values "global" (get .Values "global") }}
{{- include "cap-app-proxy.resources.tls-certs-cm" $appProxyContext }}
