{{- define "event-reporters.workflow-reporter.rbac"}}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-reporter
  labels:
    {{- include "event-reporters.workflow-reporter.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-reporter
  labels:
    app.kubernetes.io/part-of: workflow-reporter
    codefresh.io/internal: "true"
roleRef:
  apiGroup: ""
  kind: Role
  name: workflow-reporter
subjects:
  - kind: ServiceAccount
    name: {{ include "event-reporters.workflow-reporter.serviceAccountName" .}}
{{- end }}
