{{- define "event-reporters.workflow-reporter.sensor"}}
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: workflow-reporter
  labels:
    {{- include "event-reporters.workflow-reporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.workflow.sensor.replicas }}
  dependencies:
    - eventName: workflows
      eventSourceName: workflow-reporter
      name: workflows
  eventBusName: {{ default "codefresh-eventbus" .Values.global.runtime.eventBus.name }}
  template:
    serviceAccountName: {{ include "event-reporters.workflow-reporter.serviceAccountName" .}}
    container:
      name: ""
      {{- include "codefresh-gitops-runtime.components.common_helpers.container-templates.env-vars" .Values.workflow.sensor.env  | nindent 6 }}
      resources:
      {{- with .Values.workflow.sensor.resources  }}
        {{- . | toYaml | nindent 8 }}
      {{- end }}
    tolerations:
    {{- with .Values.workflow.sensor.tolerations | default .Values.global.tolerations}}
      {{- . | toYaml | nindent 6 }}
    {{- end }}
    nodeSelector:
    {{- with .Values.workflow.sensor.nodeSelector | default .Values.global.nodeSelector }}
      {{- . | toYaml | nindent 6 }}
    {{- end }}
    affinity:
    {{- with .Values.affinity }}
      {{- . | toYaml | nindent 6 }}
    {{- end }}
  triggers:
  {{- include "event-reporters.http.trigger" (dict "name" "workflows" "Values" .Values "payloadDest" "data.object" "retryStrategy" .Values.workflow.sensor.retryStrategy) | nindent 4 }}
  {{- include "event-reporters.log.trigger" (.Values.workflow.sensor.logging) | nindent 4 }}
{{- end }}
