{{- define "event-reporters.workflow-reporter.sa"}}
  {{- if .Values.workflow.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "event-reporters.workflow-reporter.serviceAccountName" .}}
  labels:
    {{- include "event-reporters.workflow-reporter.labels" . | nindent 4 }}
  {{- end }}
{{- end }}