{{- $eventReporterContext := deepCopy . }}
{{- $_ := set $eventReporterContext "Values" (get .Values "event-reporters") }}
{{- $_ := set $eventReporterContext.Values "global" (get .Values "global") }}
# should allow overwriting in values.yaml
{{- $argoCDServerServiceName := (include "codefresh-gitops-runtime.argocd.server.servicename" .) -}}
{{- $argoCDServerServicePort := ( include "codefresh-gitops-runtime.argocd.server.serviceport" . ) -}}
{{- if $eventReporterContext.Values.events.argoCDServerServiceName -}}
  {{ $argoCDServerServiceName = $eventReporterContext.Values.events.argoCDServerServiceName }}
{{- end -}}
{{- if $eventReporterContext.Values.events.argoCDServerServicePort -}}
  {{ $argoCDServerServicePort = $eventReporterContext.Values.events.argoCDServerServicePort }}
{{- end -}}
{{- $_ := set $eventReporterContext.Values.events "argoCDServerServiceName" $argoCDServerServiceName }}
{{- $_ := set $eventReporterContext.Values.events "argoCDServerServicePort" $argoCDServerServicePort }}
{{- include "event-reporters.events-reporter.eventsource" $eventReporterContext }}