{{- define "argo-api-gateway.resources.configmap.defaults" }}
argocd.server: {{ include "codefresh-gitops-runtime.argocd.server.no-protocol-url" . }}
repo.server: {{ include "codefresh-gitops-runtime.argocd.reposerver.url" . }}
redis.server: {{ include "codefresh-gitops-runtime.argocd.redis.url" . }}
{{- end }}

{{- $defaultConfig := (include "argo-api-gateway.resources.configmap.defaults" . | fromYaml ) }}
{{- $overrides := index .Values "argo-api-gateway" "config" | default dict }}
{{- $mergedConfig := mergeOverwrite $defaultConfig $overrides }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: argo-api-gateway-cmd-params-cm
  labels:
    {{- include "argo-api-gateway.labels" . | nindent 4 }}
data:
  {{- $mergedConfig | toYaml | nindent 2 }}
  {{- if index .Values "argo-cd" "enabled" }}
  foo: bar
  {{- else }}
  baz: qux
  {{- end }}
