{{- $context := deepCopy . }}
{{- $_ := set $context "Values" (deepCopy (get .Values "argo-api-gateway")) }}
{{- $_ := set $context.Values "global" (deepCopy (get .Values "global")) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "argo-api-gateway.serviceAccountName" $context }}
  labels:
    {{- include "argo-api-gateway.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "argo-api-gateway.fullname" . }}
  labels:
    {{- include "argo-api-gateway.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - ''
    resources:
    - configmaps
    - secrets
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ''
    - apps
    resources:
    - deployments
    - podtemplates
    verbs:
    - patch
  - apiGroups:
    - apps
    resources:
    - replicasets
    verbs:
    - list
    - patch
  - apiGroups:
    - argoproj.io
    resources:
    - rollouts
    - rollouts/status
    verbs:
    - get
    - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "argo-api-gateway.fullname" . }}
  labels:
    {{- include "argo-api-gateway.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "argo-api-gateway.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "argo-api-gateway.serviceAccountName" $context }}
    namespace: {{ .Release.Namespace }}
