 {{- define "cap-app-proxy.image-enrichment.resources.sa" }}
  {{- $enrichmentValues := get .Values "image-enrichment" }}
  {{- if $enrichmentValues.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $enrichmentValues.serviceAccount.name }}
  labels:
    {{- include "cap-app-proxy.labels" . | nindent 4 }}
    {{- with $enrichmentValues.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}