{{- define "event-reporters.events-reporter.eventsource"}}
apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  labels:
    {{- include "event-reporters.events-reporter.labels" . | nindent 4}}
  name: events-reporter
spec:
  replicas: {{ .Values.events.eventSource.replicas }}
  eventBusName: {{ default "codefresh-eventbus" .Values.global.runtime.eventBus.name }}
  generic:
    events:
      authSecret:
        key: token
        name: argocd-token
      config: '{}'
      insecure: true
      url: {{ printf "%s:%s" .Values.events.argoCDServerServiceName .Values.events.argoCDServerServicePort }}
  template:
    serviceAccountName: {{ include "event-reporters.events-reporter.serviceAccountName" .}}
    container:
      resources:
      {{- with .Values.events.eventSource.resources  }}
        {{- . | toYaml | nindent 8 }}
      {{- end }}
    tolerations:
    {{- with .Values.events.eventSource.tolerations }}
      {{- . | toYaml | nindent 6 }}
    {{- end }}
    nodeSelector:
    {{- with .Values.events.eventSource.nodeSelector }}
      {{- . | toYaml | nindent 6 }}
    {{- end }}
    affinity:
    {{- with .Values.events.eventSource.affinity }}
      {{- . | toYaml | nindent 6 }}
    {{- end }}
{{- end }}