{{- define "event-reporters.events-reporter.sensor"}}
apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: events-reporter
  labels:
    {{- include "event-reporters.events-reporter.labels" . | nindent 4}}
spec:
  replicas: {{ .Values.events.sensor.replicas }}
  dependencies:
  - name: events
    eventSourceName: events-reporter
    eventName: events
  eventBusName: {{ default "codefresh-eventbus" .Values.global.runtime.eventBus.name }}
  template:
    serviceAccountName: {{ include "event-reporters.events-reporter.serviceAccountName" .}}
    container:
      resources:
      {{- with .Values.events.sensor.resources  }}
        {{- . | toYaml | nindent 8 }}
      {{- end }}
    tolerations:
    {{- with .Values.events.sensor.tolerations }}
      {{- . | toYaml | nindent 6 }}
    {{- end }}
    nodeSelector:
    {{- with .Values.events.sensor.nodeSelector }}
      {{- . | toYaml | nindent 6 }}
    {{- end }}
    affinity:
    {{- with .Values.events.sensor.affinity }}
      {{- . | toYaml | nindent 6 }}
    {{- end }}
  triggers:
    {{- include "event-reporters.http.trigger" (dict "name" "events" "Values" .Values "payloadDest" "data") | nindent 4 }}
{{- end }}
