{{- define "codefresh-gitops-runtime.components.common_helpers.container-templates.env-vars" -}}
  {{- if . -}}
    {{- if  not (kindIs "map" .) -}}
      {{ fail "ERROR: env block must be a map"}}
    {{- end -}}
  {{- end -}}
  {{- if empty . -}}
env: []
  {{- else -}}
env:
    {{- range $name, $val := . }}
      {{- if kindIs "string" $val}}
- name: {{ $name }}
  value: {{ $val }}
      {{- else if kindIs "map" $val}}
        {{- if hasKey $val "valueFrom" }}
          {{- if or (hasKey $val.valueFrom "secretKeyRef") (hasKey $val.valueFrom "configMapKeyRef") (hasKey $val.valueFrom "fieldRef") }}
- name: {{ $name }}
{{- $val | toYaml | nindent 2}}        
          {{- else}}
            {{ fail "ERROR: Only secretKeyRef/configMapKeyRef/fieldRef are supported for valueFrom block for environment variables" }}
          {{- end}}
        {{- else }}
          {{ fail "ERROR: Cannot generate environment variables only strings and valueFrom are supported"}}
        {{- end }}
      {{- else }}
        {{ fail "ERROR: Only maps and string are supported for environment variables"}}
      {{- end }}
    {{- end }}
  {{- end }}
{{- end -}}