
{{- define "gitops-operator.resources.auth-proxy-rbac" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.singleNamespace | ternary "Role" "ClusterRole" }}
metadata:
  labels:
    {{- include "gitops-operator.selectorLabels" . | nindent 4 }}
  name: codefresh-gitops-operator-proxy
rules:
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create

---
apiVersion: rbac.authorization.k8s.io/v1
kind: {{ .Values.singleNamespace | ternary "RoleBinding" "ClusterRoleBinding" }}
metadata:
  labels:
    {{- include "gitops-operator.selectorLabels" . | nindent 4 }}
  name: codefresh-gitops-operator-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: {{ .Values.singleNamespace | ternary "Role" "ClusterRole" }}
  name: codefresh-gitops-operator-proxy
subjects:
- kind: ServiceAccount
  name: {{ include "gitops-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
