
{{- define "gitops-operator.resources.restricted_git_source_rbac" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "gitops-operator.selectorLabels" . | nindent 4 }}
  name: restrictedgitsource-editor
rules:
- apiGroups:
  - csdp.codefresh.io
  resources:
  - restrictedgitsources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - csdp.codefresh.io
  resources:
  - restrictedgitsources/status
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "gitops-operator.selectorLabels" . | nindent 4 }}
  name: restrictedgitsource-viewer
rules:
- apiGroups:
  - csdp.codefresh.io
  resources:
  - restrictedgitsources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - csdp.codefresh.io
  resources:
  - restrictedgitsources/status
  verbs:
  - get
{{- end }}
