
{{- define "gitops-operator.resources.restricted-git-source-rbac" }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "gitops-operator.selectorLabels" . | nindent 4 }}
  name: restrictedgitsource-editor
rules:
- apiGroups:
  - codefresh.io
  resources:
  - restrictedgitsources
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - codefresh.io
  resources:
  - restrictedgitsources/status
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    {{- include "gitops-operator.selectorLabels" . | nindent 4 }}
  name: restrictedgitsource-viewer
rules:
- apiGroups:
  - codefresh.io
  resources:
  - restrictedgitsources
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - codefresh.io
  resources:
  - restrictedgitsources/status
  verbs:
  - get

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "gitops-operator.selectorLabels" . | nindent 4 }}
  name: restrictedgitsource-editor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: restrictedgitsource-editor
subjects:
- kind: ServiceAccount
  name: {{ include "gitops-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "gitops-operator.selectorLabels" . | nindent 4 }}
  name: restrictedgitsource-viewer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: restrictedgitsource-viewer
subjects:
- kind: ServiceAccount
  name: {{ include "gitops-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
