apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ printf "%s-%s-application-controller" .Release.Name (get .Values "argo-cd").fullnameOverride | trunc 63 | trimSuffix "-" }}
  labels:
    {{- include "codefresh-gitops-runtime.labels" . | nindent 4 }}
rules:
  - apiGroups:
    - '*'
    resources:
    - '*'
    verbs:
    - '*'
  - nonResourceURLs:
    - '*'
    verbs:
    - '*'
