{{- if and (not (index .Values "argo-cd" "enabled")) }}
  {{- $cfArgoCdExtrasContext := (index .Subcharts "cf-argocd-extras")}}

  {{- $_ := set (index $cfArgoCdExtrasContext.Values.eventReporter.configMaps "cmd-params-cm" "data") "argocd.server" (include "codefresh-gitops-runtime.argocd.server.no-protocol-url" . ) }}
  {{- $_ := set (index $cfArgoCdExtrasContext.Values.eventReporter.configMaps "cmd-params-cm" "data") "redis.server" (include "codefresh-gitops-runtime.argocd.redis.url" . ) }}

  {{- $_ := set (index $cfArgoCdExtrasContext.Values.sourcesServer.configMaps "cmd-params-cm" "data") "argocd.server" (include "codefresh-gitops-runtime.argocd.server.no-protocol-url" . ) }}
  {{- $_ := set (index $cfArgoCdExtrasContext.Values.sourcesServer.configMaps "cmd-params-cm" "data") "redis.server" (include "codefresh-gitops-runtime.argocd.redis.url" . ) }}
  {{- $_ := set (index $cfArgoCdExtrasContext.Values.sourcesServer.configMaps "cmd-params-cm" "data") "repo.server" (include "codefresh-gitops-runtime.argocd.reposerver.url" . ) }}

  {{- if and (index .Values "global" "external-argo-cd" "tokenSecretKeyRef") }}
    {{- $_ := set $cfArgoCdExtrasContext.Values.eventReporter.container.env "ARGO_CD_TOKEN_SECRET_NAME" (index .Values "global" "external-argo-cd" "tokenSecretKeyRef" "name" ) }}
    {{- $_ := set $cfArgoCdExtrasContext.Values.eventReporter.container.env "ARGO_CD_TOKEN_SECRET_KEY" (index .Values "global" "external-argo-cd" "tokenSecretKeyRef" "key" ) }}
    {{- $_ := set $cfArgoCdExtrasContext.Values.sourcesServer.container.env "ARGO_CD_TOKEN_SECRET_NAME" (index .Values "global" "external-argo-cd" "tokenSecretKeyRef" "name" ) }}
    {{- $_ := set $cfArgoCdExtrasContext.Values.sourcesServer.container.env "ARGO_CD_TOKEN_SECRET_KEY" (index .Values "global" "external-argo-cd" "tokenSecretKeyRef" "key" ) }}
  {{- end }}

  {{- include "cf-argocd-extras.event-reporter.resources" $cfArgoCdExtrasContext }}

  {{- include "cf-argocd-extras.sources-server.resources" $cfArgoCdExtrasContext }}
{{- end }}
