{{/*
Workflow reporter service account for backward compatibility
*/}}
{{- if (index .Values "event-reporters" "workflow" "serviceAccount" "create") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "event-reporters.workflow-reporter.serviceAccountName" . }}
  labels:
    {{- include "event-reporters.workflow-reporter.labels" . | nindent 4 }}
{{- end }} 