{{/*
Workflow reporter RBAC for backward compatibility
*/}}
{{- if (index .Values "event-reporters" "workflow" "serviceAccount" "create") }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: workflow-reporter
  labels:
    {{- include "event-reporters.workflow-reporter.labels" . | nindent 4 }}
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: workflow-reporter
  labels:
    {{- include "event-reporters.workflow-reporter.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: workflow-reporter
subjects:
  - kind: ServiceAccount
    name: {{ include "event-reporters.workflow-reporter.serviceAccountName" . }}
{{- end }} 